---
title: "Why you should use R"
author: "Andrew & Tony"
date: "17 October 2017"
output: 
  ioslides_presentation: 
    df_print: kable
    theme: flatly
    toc: yes
params:
   year: 2015
   tail: 30
   style: atlas
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, 
  message = FALSE,
	warning = FALSE)

```

## Data overview

```{r, include=FALSE}
library(ggplot2)
library(extrafont)
library(dplyr)

library(wbgcharts)
library(wbgmaps)
library(wbggeo)
library(wbstats) # Getting 

style <- get(paste0("style_",params$style))(9)

# Import the data from API
indicators <- c("SH.H2O.SAFE.ZS", "SH.H2O.SAFE.RU.ZS")
df <- wbgdata(country = "countries_only", indicator = indicators, startdate = params$year, enddate = params$year, indicator.wide = FALSE, cache = wbgcharts:::wb_newcache)

# Transform the data - find the bottom 30 by rural
bottom <- df %>%
  filter(complete.cases(.)) %>%
  filter(indicatorID == "SH.H2O.SAFE.RU.ZS") %>%
  arrange(-value) %>%
  tail(params$tail) %>%
  pull(iso3c)

df_dotplot <- df %>%
  filter(complete.cases(.)) %>%
  filter(iso3c %in% bottom) %>%
  mutate(iso3c = factor(iso3c, levels = bottom))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
head(df_dotplot %>% arrange(iso3c, indicatorID))
```

## Plot one

```{r echo=FALSE, message=FALSE, warning=FALSE}
grid::grid.newpage()

p <- ggplot(data = df_dotplot, aes(x = value, y = iso3c, color = indicatorID, shape = indicatorID)) +
  geom_other_dotplot(aes(y = iso3c), size.line = 0.25) +
  geom_other_dotplot_label(
    aes(x = value, y = iso3c, label = wbgref$countries$labels[as.character(iso3c)]),
    side = "left", nudge_x = -1,
    size = style$gg_text_size * 0.8, color = style$theme()$text$colour,
    family = style$theme()$text$family
  ) +
  scale_x_continuous(limits = c(20, 80)) +
  scale_color_manual(values=style$colors$categorical, labels = c("Rural", "National")) +
  scale_shape_manual(values=style$shapes$categorical, labels = c("Rural", "National")) +
  style$theme() +
  style$theme_barchart() +
  theme(axis.text.y = element_blank(),
        legend.position = c(0.9,1), legend.justification = c(1,1),
        legend.direction = "horizontal", legend.margin = margin())

figure(
  p,
  aspect_ratio = 3/4,
  title = "People in rural areas suffer from especially low access to water...",
  subtitle = paste0("Share of population with access to an improved water source, national average and rural (%), ", params$year),
  source = paste("Source:", wbg_source(indicators))
)
```

## Plot two

```{r echo=FALSE, message=FALSE, warning=FALSE}
grid::grid.newpage()

df_map <- df %>%
  filter(indicatorID == "SH.H2O.SAFE.ZS")

df_map$bin <- supercut(
    df_map$value,
    c("[0,25)","[25,50)","[50,75)", "[75,100]"),
    c("0-25", "25-50", "50-75", "75-100")
)

pg <- wbg_choropleth(df_map, wbgmaps[["low"]], style, "bin", aspect_ratio = 2)

figure(
  pg,
  theme = style$theme(),
  aspect_ratio = 5/4,
  title = "Those who lack improved water sources are concentrated largely in Sub-Saharan Africa",
  subtitle = paste0(wbg_name(indicators[1]), ", ", params$year),
  source = paste("Source:", wbg_source(indicators[1]))
)
```